<?php

namespace DreamBundle\Repository;

/**
 * DreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestDreams(){
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.created', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }

    public function getPopularDreams(){
        $qb = $this->createQueryBuilder('g')
            ->select("g")

            ->addOrderBy('g.likes+g.unlikes', 'DESC');

        return $qb->getQuery()
            ->getResult();


    }
    public function getBestDreams(){
        $qb = $this->createQueryBuilder('g')
            ->select("g")
            ->addOrderBy('g.likes', 'DESC');

        return $qb->getQuery()
            ->getResult();


    }
    public function getNewDreams(){
        $qb = $this->createQueryBuilder('g')
            ->select("g")
            ->addOrderBy('g.created', 'DESC');

        return $qb->getQuery()
            ->getResult();


    }



}
